name: Build & Test RobloxGuard
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/RobloxGuard.sln

      - name: Build (Release)
        run: dotnet build ./src/RobloxGuard.sln -c Release --no-restore

      - name: Run Tests
        run: dotnet test ./src/RobloxGuard.sln -c Release --no-build --verbosity normal

      - name: Publish Single-File EXE
        run: dotnet publish ./src/RobloxGuard.UI/RobloxGuard.UI.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true -o out/publish

      - name: Verify EXE
        shell: pwsh
        run: |
          $exe = "out/publish/RobloxGuard.exe"
          if (Test-Path $exe) {
            $size = [math]::Round((Get-Item $exe).Length / 1MB, 2)
            Write-Host "✓ Build successful: RobloxGuard.exe ($size MB)"
          } else {
            Write-Host "✗ Build failed: RobloxGuard.exe not found"
            exit 1
          }

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RobloxGuard-Build
          path: out/publish/RobloxGuard.exe
