name: Release
on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/RobloxGuard.sln

      - name: Build (Release)
        run: dotnet build ./src/RobloxGuard.sln -c Release --no-restore

      - name: Run Tests
        run: dotnet test ./src/RobloxGuard.sln -c Release --no-build --verbosity normal

      - name: Publish Single-File EXE
        run: dotnet publish ./src/RobloxGuard.UI/RobloxGuard.UI.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true -o out/publish

      - name: Verify EXE Built Successfully
        shell: pwsh
        run: |
          $exe = "out/publish/RobloxGuard.exe"
          if (Test-Path $exe) {
            $size = [math]::Round((Get-Item $exe).Length / 1MB, 2)
            Write-Host "✓ EXE built successfully: $size MB"
          } else {
            Write-Host "✗ EXE build failed!"
            exit 1
          }

      - name: Generate SHA256 Checksums
        shell: pwsh
        run: |
          $exe = "out/publish/RobloxGuard.exe"
          if (Test-Path $exe) {
            $hash = (Get-FileHash -Path $exe -Algorithm SHA256).Hash
            "$hash  RobloxGuard.exe" | Out-File out/RobloxGuard.exe.sha256
            Write-Host "✓ Checksum generated"
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/publish/RobloxGuard.exe
            out/RobloxGuard.exe.sha256
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
