name: Release
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: RobloxGuard-artifacts
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
